name:                EfficientSetOptimizer
version:             0.1.0.0
github:              "githubuser/EfficientSetOptimizer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/EfficientSetOptimizer#readme>

dependencies:
- base 
#- NadirSolver
#- TamVan19
- lens  
- array
- mtl
- containers
- random
- deepseq



ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src
  other-extensions:    ForeignFunctionInterface, ConstrainedClassMethods, StrictData
  c-sources:
      - cbits/IloBoolVar.cpp
      - cbits/IloCplex.cpp 
      - cbits/IloEnv.cpp
      - cbits/IloModel.cpp
      - cbits/IloNumVar.cpp 
      - cbits/IloObjective.cpp 
      - cbits/IloRange.cpp 
      - cbits/MIPInfoCallback.cpp 
      - cbits/MIPIncumbentCallback.cpp
  extra-libraries: gomp concert ilocplex cplex m pthread stdc++ dl
  #cc-options: -m64 -O3 -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD #-ldl
  cc-options: -m64 -O3 -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD -ldl
  
  include-dirs: /home/sat/cplex2210/cplex/include /home/sat/cplex2210/concert/include
  extra-lib-dirs: /home/sat/cplex2210/cplex/lib/x86-64_linux/static_pic /home/sat/cplex2210/concert/lib/x86-64_linux/static_pic


executables:
  EfficientSetOptimizer-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - EfficientSetOptimizer
    cc-options: -m64 -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD

tests:
  EfficientSetOptimizer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EfficientSetOptimizer
