name:                EfficientSetOptimizer
version:             0.1.0.0
github:              "githubuser/EfficientSetOptimizer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/EfficientSetOptimizer#readme>

dependencies:
- base >= 4.7 && < 5
#- NadirSolver
- TamVan19
- lens  >= 4.19 && < 5
- array
- mtl
- containers



ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  cc-options: -m64 -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD

executables:
  EfficientSetOptimizer-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - EfficientSetOptimizer
    cc-options: -m64 -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD

tests:
  EfficientSetOptimizer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EfficientSetOptimizer
